# This strategy attempts to reseed in the fairest/broadest way possible
# It prioritizes torrents with the lowest number of seeders and the highest number of leechers

reseedTorrent:
  endpoint: http://192.168.11.21:8083/transmission/rpc
  maxActiveTorrents: 10
  dryRun: true

  predicates:
    - name: LeecherCount
      config:
        minimum: 1

  comparators:
    - name: SeederCount
      config:
        sortOrder: ASCENDING
    - name: LeecherCount
      config:
        sortOrder: DESCENDING