# This is the most basic Strategy
# It will restart any stopped/paused torrents with at least one leecher

reseedTorrent:
  endpoint: http://192.168.11.21:8084/transmission/rpc
  maxActiveTorrents: 10
  dryRun: true

  predicates:
    - name: LeecherCount
      config:
        minimum: -1