# This Strategy only seeds torrents with 0 seeds and at least 1 leecher

reseedTorrent:
  endpoint: http://192.168.11.21:8084/transmission/rpc
  maxActiveTorrents: 10
  dryRun: true

  predicates:
    - name: LeecherCount
      config:
        minimum: 1
    - name: SeederCount
      config:
        maximum: 0
